//共用
export const BASE_LOADING = 'BASE_LOADING';
export const BASE_MESSAGE = 'BASE_MESSAGE';
export const BASE_WINDOW_INNER_HEIGHT = 'BASE_WINDOW_INNER_HEIGHT';
export const BASE_GLOBAL_AUTH = 'BASE_GLOBAL_AUTH';

//登录页面
export const LOGIN_INIT_STATE = 'LOGIN_INIT_STATE';
export const LOGIN_SAVE_USER_NAME = 'LOGIN_SAVE_USER_NAME';
export const LOGIN_SAVE_PASSWORD = 'LOGIN_SAVE_PASSWORD';
export const LOGIN_SAVE_LOGIN_INFO = 'LOGIN_SAVE_LOGIN_INFO';
export const LOGIN_DELETE_LOGIN_INFO = 'LOGIN_DELETE_LOGIN_INFO';
export const LOGIN_BRAND = 'LOGIN_BRAND';

//门店管理
export const MERCHANT_INIT_STATE = 'MERCHANT_INIT_STATE';
export const MERCHANT_SET_ID = 'MERCHANT_SET_ID';

// 采购管理
export const PURCHASE_SUPPLIER_INIT_STATE = 'PURCHASE_SUPPLIER_INIT_STATE';
export const PURCHASE_SUPPLIER_SET_LIST_ITEM = 'PURCHASE_SUPPLIER_SET_LIST_ITEM';
export const PURCHASE_SUPPLIER_SET_ITEM_APPROVE = 'PURCHASE_SUPPLIER_SET_ITEM_APPROVE';
export const PURCHASE_SUPPLIER_SET_ITEM_FREEZE = 'PURCHASE_SUPPLIER_SET_ITEM_FREEZE';

export const PURCHASE_ITEM_INIT_STATE = 'PURCHASE_ITEM_INIT_STATE';
export const PURCHASE_ITEM_SET_LIST_ITEM = 'PURCHASE_ITEM_SET_LIST_ITEM';
export const PURCHASE_ITEM_SET_ITEM_FIRST_CHECKED = 'PURCHASE_ITEM_SET_ITEM_FIRST_CHECKED';
export const PURCHASE_ITEM_SET_ITEM_SECOND_CHECKED = 'PURCHASE_ITEM_SET_ITEM_SECOND_CHECKED';
export const PURCHASE_ITEM_SET_ITEM_DECLINED = 'PURCHASE_ITEM_SET_ITEM_DECLINED';

export const PURCHASE_WAREHOUSE_INIT_STATE = 'PURCHASE_WAREHOUSE_INIT_STATE';
export const PURCHASE_WAREHOUSE_SET_LIST_ITEM = 'PURCHASE_WAREHOUSE_SET_LIST_ITEM';

export const PURCHASE_FINANCE_INIT_STATE = 'PURCHASE_FINANCE_INIT_STATE';
export const PURCHASE_FINANCE_SET_LIST_ITEM = 'PURCHASE_FINANCE_SET_LIST_ITEM';

//商品管理
export const ITEM_ITEM_INIT_STATE_DATA = 'ITEM_ITEM_INIT_STATE_DATA';
export const ITEM_ITEM_SAVE_DATA_ITEM = 'ITEM_ITEM_SAVE_DATA_ITEM';
export const ITEM_ITEM_DETAIL = 'ITEM_ITEM_DETAIL';
export const ITEM_ITEM_IS_SHOW_ADD_EDIT = 'ITEM_ITEM_IS_SHOW_ADD_EDIT';
export const ITEM_ITEM_IS_SHOW_DETAIL = 'ITEM_ITEM_IS_SHOW_DETAIL';
export const ITEM_ITEM_IS_SHOW_EDIT_TAGS = 'ITEM_ITEM_IS_SHOW_EDIT_TAGS';
export const ITEM_ITEM_IS_SHOW_EDIT_CODE = 'ITEM_ITEM_IS_SHOW_EDIT_CODE';

export const ITEM_PRICING_INIT_STATE_DATA = 'ITEM_PRICING_INIT_STATE_DATA';
export const ITEM_PRICING_SAVE_DATA_ITEM = 'ITEM_PRICING_SAVE_DATA_ITEM';
export const ITEM_PRICING_IS_SHOW_EDIT = 'ITEM_PRICING_IS_SHOW_EDIT';
export const ITEM_PRICING_SAVE_EDIT_DATA = 'ITEM_PRICING_SAVE_EDIT_DATA';

// 全场营销
export const ITEM_SCOPE_PROMOTION_INIT_STATE = 'ITEM_PROMOTION_INIT_STATE';
export const ITEM_SCOPE_PROMOTION_SET_LIST_ITEM = 'ITEM_PROMOTION_SET_LIST_ITEM';
export const ITEM_SCOPE_PROMOTION_SET_ITEM_START = 'ITEM_PROMOTION_SET_ITEM_START';
export const ITEM_SCOPE_PROMOTION_SET_ITEM_HALT = 'ITEM_PROMOTION_SET_ITEM_HALT';

// 优惠券
export const ITEM_COUPON_INIT_STATE = 'ITEM_COUPON_INIT_STATE';
export const ITEM_COUPON_SET_LIST_ITEM = 'ITEM_COUPON_SET_LIST_ITEM';

// 社区团购
export const GROUP_BUY_INIT_STATE = 'GROUP_BUY_INIT_STATE';
export const GROUP_BUY_LIST = 'GROUP_BUY_LIST';
export const GROUP_BUY_ITEM_LIST = 'GROUP_BUY_ITEM_LIST';
export const GROUP_BUY_DETAIL = 'GROUP_BUY_DETAIL';
export const GROUP_BUY_STORE_LIST = 'GROUP_BUY_STORE_LIST';
export const GROUP_BUY_STORE_MEMBER_LIST = 'GROUP_BUY_STORE_MEMBER_LIST';

// 财务管理
export const FINANCE_BALANCE_INIT_STATE = 'FINANCE_BALANCE_INIT_STATE';
export const FINANCE_BALANCE_SET_LIST_ITEM = 'FINANCE_BALANCE_SET_LIST_ITEM';

export const FINANCE_APPROVE_INIT_STATE = 'FINANCE_APPROVE_INIT_STATE';
export const FINANCE_APPROVE_SET_LIST_ITEM = 'FINANCE_APPROVE_SET_LIST_ITEM';

//运营管理
export const OPERATE_LINE_INIT_STATE_DATA = 'OPERATE_LINE_INIT_STATE_DATA';
export const OPERATE_LINE_SAVE_DATA_ITEM = 'OPERATE_LINE_SAVE_DATA_ITEM';
export const OPERATE_LINE_DETAIL = 'OPERATE_LINE_DETAIL';
export const OPERATE_LINE_IS_SHOW_ADD_EDIT = 'OPERATE_LINE_IS_SHOW_ADD_EDIT';

export const OPERATE_RECEIVING_INIT_STATE_DATA = 'OPERATE_RECEIVING_INIT_STATE_DATA';
export const OPERATE_RECEIVING_SAVE_DATA_ITEM = 'OPERATE_RECEIVING_SAVE_DATA_ITEM';
export const OPERATE_RECEIVING_IS_SHOW_ALLOT = 'OPERATE_RECEIVING_IS_SHOW_ALLOT';
export const OPERATE_RECEIVING_SAVE_DISTRIBUTE_STORES_ITEM = 'OPERATE_RECEIVING_SAVE_DISTRIBUTE_STORES_ITEM';
export const OPERATE_RECEIVING_IS_SHOW_EDIT_NUMBER = 'OPERATE_RECEIVING_IS_SHOW_EDIT_NUMBER';
export const OPERATE_RECEIVING_EDIT_NUMBER_DATA = 'OPERATE_RECEIVING_EDIT_NUMBER_DATA';
export const OPERATE_RECEIVING_OPT_DATA = 'OPERATE_RECEIVING_OPT_DATA';
export const OPERATE_RECEIVING_IS_SHOW_WEIGH = 'OPERATE_RECEIVING_IS_SHOW_WEIGH';
export const OPERATE_RECEIVING_WEIGH_STORE_ITEM = 'OPERATE_RECEIVING_WEIGH_STORE_ITEM';
export const OPERATE_RECEIVING_WEIGH_ITEMS_ITEM = 'OPERATE_RECEIVING_WEIGH_ITEMS_ITEM';
export const OPERATE_RECEIVING_WEIGH_STORE_ITEMS_LIST = 'OPERATE_RECEIVING_WEIGH_STORE_ITEMS_LIST';
export const OPERATE_RECEIVING_WEIGH_IS_SHOW_EDIT = 'OPERATE_RECEIVING_WEIGH_IS_SHOW_EDIT';
export const OPERATE_RECEIVING_WEIGH_EDIT_DATA = 'OPERATE_RECEIVING_WEIGH_EDIT_DATA';

//订单管理
export const ORDER_INIT_STATE_DATA = 'ORDER_INIT_STATE_DATA';
export const ORDER_SAVE_DATA_ITEM = 'ORDER_SAVE_DATA_ITEM';
export const ORDER_SAVE_DETAIL = 'ORDER_SAVE_DETAIL';
export const ORDER_SHOW_HIDE_DETAIL = 'ORDER_SHOW_HIDE_DETAIL';
export const ORDER_SHOW_HIDE_PRICE_UPDATE = 'ORDER_SHOW_HIDE_PRICE_UPDATE';
export const ORDER_SHOW_HIDE_MANUAL_DELIVERY = 'ORDER_SHOW_HIDE_MANUAL_DELIVERY';

export const ORDER_SAVE_AFTER_SALE_DATA_ITEM = 'ORDER_SAVE_AFTERSALE_DATA_ITEM';
export const ORDER_SAVE_AFTER_SALE_DETAIL = 'ORDER_SAVE_AFTERSALE_DETAIL';
export const ORDER_SHOW_AFTER_SALE_HIDE_DETAIL = 'ORDER_SHOW_HIDE_AFTERSALE_DETAIL';
export const ORDER_SHOW_AFTER_SALE_HIDE_CLOSE = 'ORDER_SHOW_AFTER_SALE_HIDE_CLOSE';

//基础数据
export const BASIC_DATA_FRAME_INIT_STATE_DATA = 'BASIC_DATA_FRAME_INIT_STATE_DATA';
export const BASIC_DATA_FRAME_SAVE_DATA_ITEM = 'BASIC_DATA_FRAME_SAVE_DATA_ITEM';
export const BASIC_DATA_FRAME_DETAIL = 'BASIC_DATA_FRAME_DETAIL';
export const BASIC_DATA_FRAME_IS_SHOW_ADD_EDIT = 'BASIC_DATA_FRAME_IS_SHOW_ADD_EDIT';

export const BASIC_DATA_DISPLAY_CLASS_INIT_STATE_DATA = 'BASIC_DATA_DISPLAY_CLASS_INIT_STATE_DATA';
export const BASIC_DATA_DISPLAY_CLASS_SAVE_DATA_ITEM = 'BASIC_DATA_DISPLAY_CLASS_SAVE_DATA_ITEM';
export const BASIC_DATA_DISPLAY_CLASS_DETAIL = 'BASIC_DATA_DISPLAY_CLASS_DETAIL';
export const BASIC_DATA_DISPLAY_CLASS_IS_SHOW_ADD_EDIT = 'BASIC_DATA_DISPLAY_CLASS_IS_SHOW_ADD_EDIT';

export const BASIC_DATA_SYSTEM_CLASS_INIT_STATE_DATA = 'BASIC_DATA_SYSTEM_CLASS_INIT_STATE_DATA';
export const BASIC_DATA_SYSTEM_CLASS_SAVE_DATA_ITEM = 'BASIC_DATA_SYSTEM_CLASS_SAVE_DATA_ITEM';
export const BASIC_DATA_SYSTEM_CLASS_DETAIL = 'BASIC_DATA_SYSTEM_CLASS_DETAIL';
export const BASIC_DATA_SYSTEM_CLASS_IS_SHOW_ADD_EDIT = 'BASIC_DATA_SYSTEM_CLASS_IS_SHOW_ADD_EDIT';

export const BASIC_DATA_ITEM_TAGS_INIT_STATE_DATA = 'BASIC_DATA_ITEM_TAGS_INIT_STATE_DATA';
export const BASIC_DATA_ITEM_TAGS_SAVE_DATA_ITEM = 'BASIC_DATA_ITEM_TAGS_SAVE_DATA_ITEM';
export const BASIC_DATA_ITEM_TAGS_DETAIL = 'BASIC_DATA_ITEM_TAGS_DETAIL';
export const BASIC_DATA_ITEM_TAGS_IS_SHOW_ADD_EDIT = 'BASIC_DATA_ITEM_TAGS_IS_SHOW_ADD_EDIT';

export const BASIC_DATA_MERCHANT_INNER_TAGS_INIT_STATE_DATA = 'BASIC_DATA_MERCHANT_INNER_TAGS_INIT_STATE_DATA';
export const BASIC_DATA_MERCHANT_INNER_TAGS_SAVE_DATA_ITEM = 'BASIC_DATA_MERCHANT_INNER_TAGS_SAVE_DATA_ITEM';
export const BASIC_DATA_MERCHANT_INNER_TAGS_DETAIL = 'BASIC_DATA_MERCHANT_INNER_TAGS_DETAIL';
export const BASIC_DATA_MERCHANT_INNER_TAGS_IS_SHOW_ADD_EDIT = 'BASIC_DATA_MERCHANT_INNER_TAGS_IS_SHOW_ADD_EDIT';

export const BASIC_DATA_GRADE_INIT_STATE_DATA = 'BASIC_DATA_GRADE_INIT_STATE_DATA';
export const BASIC_DATA_GRADE_SAVE_DATA_ITEM = 'BASIC_DATA_GRADE_SAVE_DATA_ITEM';
export const BASIC_DATA_GRADE_DETAIL = 'BASIC_DATA_GRADE_DETAIL';
export const BASIC_DATA_GRADE_IS_SHOW_ADD_EDIT = 'BASIC_DATA_GRADE_IS_SHOW_ADD_EDIT';

export const BASIC_DATA_PROVINCE_INIT_STATE_DATA = 'BASIC_DATA_PROVINCE_INIT_STATE_DATA';
export const BASIC_DATA_PROVINCE_SAVE_DATA_ITEM = 'BASIC_DATA_PROVINCE_SAVE_DATA_ITEM';
export const BASIC_DATA_PROVINCE_DETAIL = 'BASIC_DATA_PROVINCE_DETAIL';
export const BASIC_DATA_PROVINCE_IS_SHOW_ADD_EDIT = 'BASIC_DATA_PROVINCE_IS_SHOW_ADD_EDIT';

export const BASIC_DATA_ZONE_INIT_STATE_DATA = 'BASIC_DATA_ZONE_INIT_STATE_DATA';
export const BASIC_DATA_ZONE_SAVE_DATA_ITEM = 'BASIC_DATA_ZONE_SAVE_DATA_ITEM';
export const BASIC_DATA_ZONE_DETAIL = 'BASIC_DATA_ZONE_DETAIL';
export const BASIC_DATA_ZONE_IS_SHOW_ADD_EDIT = 'BASIC_DATA_ZONE_IS_SHOW_ADD_EDIT';

export const BASIC_DATA_CITY_INIT_STATE_DATA = 'BASIC_DATA_CITY_INIT_STATE_DATA';
export const BASIC_DATA_CITY_SAVE_DATA_ITEM = 'BASIC_DATA_CITY_SAVE_DATA_ITEM';
export const BASIC_DATA_CITY_DETAIL = 'BASIC_DATA_CITY_DETAIL';
export const BASIC_DATA_CITY_IS_SHOW_ADD_EDIT = 'BASIC_DATA_CITY_IS_SHOW_ADD_EDIT';
export const BASIC_DATA_ITEM_TAGS_ICONS = 'BASIC_DATA_ITEM_TAGS_ICONS';
//系统管理
export const SYSTEM_ROLE_LIST_INIT_STATE_DATA = 'SYSTEM_ROLE_LIST_INIT_STATE_DATA';
export const SYSTEM_ROLE_LIST_SAVE_DATA_ITEM = 'SYSTEM_ROLE_LIST_SAVE_DATA_ITEM';
export const SYSTEM_ROLE_LIST_IS_SHOW_ADD_EDIT = 'SYSTEM_ROLE_LIST_IS_SHOW_ADD_EDIT';
export const SYSTEM_ROLE_LIST_SAVE_DETAIL = 'SYSTEM_ROLE_LIST_SAVE_DETAIL';
export const SYSTEM_ROLE_LIST_SAVE_PERMISSION_LIST = 'SYSTEM_ROLE_LIST_SAVE_PERMISSION_LIST';

export const SYSTEM_OPERATOR_INIT_STATE_DATA = 'SYSTEM_OPERATOR_INIT_STATE_DATA';
export const SYSTEM_OPERATOR_SAVE_DATA_ITEM = 'SYSTEM_OPERATOR_SAVE_DATA_ITEM';
export const SYSTEM_OPERATOR_IS_SHOW_RESET_PWD = 'SYSTEM_OPERATOR_IS_SHOW_RESET_PWD';
export const SYSTEM_OPERATOR_DETAIL = 'SYSTEM_OPERATOR_DETAIL';
export const SYSTEM_OPERATOR_IS_SHOW_ADD_EDIT = 'SYSTEM_OPERATOR_IS_SHOW_ADD_EDIT';

export const SYSTEM_BANNER_LIST = 'SYSTEM_BANNER_LIST';
export const SYSTEM_BANNER_IS_SHOW_ADD_EDIT = 'SYSTEM_BANNER_IS_SHOW_ADD_EDIT';
export const SYSTEM_BANNER_DETAIL = 'SYSTEM_BANNER_DETAIL';
export const SYSTEM_BRAND = 'SYSTEM_BRAND';
export const SYSTEM_BRAND_SERVICE = 'SYSTEM_BRAND_SERVICE';



