// import ButtonGroup from './ButtonGroup';
// import QueryItem from './QueryItem';
// import ToPrice from './ToPrice';
// import TableOperate from './TableOperate';
// import OmissionText from './OmissionText';
// import CollapseQuery from './CollapseQuery';
// import FormArea from './FormArea';
//
//
// export {ButtonGroup, QueryItem, ToPrice, TableOperate, OmissionText, CollapseQuery, FormArea}

export { default as Autocomplete } from './Autocomplete';
export { default as Avatar } from './Avatar';
export { default as Button } from './Button';
export { default as ButtonGroup } from './ButtonGroup';
export { default as CollapseQuery } from './CollapseQuery';
export { default as Dialog } from './Dialog';
export { default as FormArea } from './FormArea';
export { default as GlobalProvince } from './GlobalProvince';
export { default as ImagePreview } from './ImagePreview';
export { default as Label } from './Label';
export { default as NumberKey } from './NumberKey';
export { default as OmissionText } from './OmissionText';
export { default as Pagination } from './Pagination';
export { default as PwdModify } from './PwdModify';
export { default as QueryItem } from './QueryItem';
export { default as QuillEditor } from './QuillEditor';
export { default as Search } from './Search';
export { default as SearchItem } from './SearchItem';
export { default as SearchGroupItem } from './SearchGroupItem';
export { default as SelectBuyer } from './SelectBuyer';
export { default as SelectCity } from './SelectCity';
export { default as SelectCityMulti } from './SelectCityMulti';
export { default as SelectDisplayClass } from './SelectDisplayClass';
export { default as SelectDistributorMulti } from './SelectDistributorMulti';
export { default as SelectFrame } from './SelectFrame';
export { default as SelectLineMulti } from './SelectLineMulti';
export { default as SelectLineOperate } from './SelectLineOperate';
export { default as SelectLineQuery } from './SelectLineQuery';
export { default as SelectProvince } from './SelectProvince';
export { default as SelectProvinceMulti } from './SelectProvinceMulti';
export { default as SelectProvinceQuery } from './SelectProvinceQuery';
export { default as SelectTag } from './SelectTag';
export { default as SelectZone } from './SelectZone';
export { default as SelectZoneMulti } from './SelectZoneMulti';
export { default as SelectZoneQuery } from './SelectZoneQuery';
export { default as SortingIndicator } from './SortingIndicator';
export { default as TableOperate } from './TableOperate';
export { default as ToPrice } from './ToPrice';
export { default as UploadImg } from './UploadImg';
